from enum import Enum


class XlsxTemplate(Enum):
    dicinfo = """insert into dicinfo (DICID,REFID,PARENTDICID,DCODE,DICNAME,FULLNAME,COMMENT,TXTCODE,DICORDER,EXTCODE,REKVINT1,DISDATE,SIMPLENAME,REKVINT2,REKVTEXT1,REKVINT3,REKVFLOAT,BDATE,REKVINT4,REKVFLOAT2,REKVINT5,REKVINT6,REKVINT7,REKVINT8,REKVINT9,REKVINT10,REKVINT11)  values ({DICID},{REFID},{PARENTDICID},{DCODE},'{DICNAME}','{FULLNAME}','{COMMENT}',{TXTCODE},{DICORDER},{EXTCODE},{REKVINT1},{DISDATE},{SIMPLENAME},{REKVINT2},'{REKVTEXT1}',{REKVINT3},{REKVFLOAT},{BDATE},{REKVINT4},{REKVFLOAT2},{REKVINT5},{REKVINT6},{REKVINT7},{REKVINT8},{REKVINT9},{REKVINT10},{REKVINT11});\n"""


